### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [dcdepaepe/staticRails#1]
This is looking very good, apart from some of the indentation we may as well fix now, since we'll be building off this project in the future. The standard indentation for Ruby (`.rb`) files is two-space soft-tabs and I can see that in files like `application_helper.rb` you've implemented this very well. In Rails projects however, it's actually best practice to have _every_ file use two-space soft-tabs.

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.

**Comment by dcdepaepe** [comment]
Should be all set.

**Comment by chrisvfritz** [comment]
:+1:
